# Generated by Django 2.0 on 2018-08-29 19:33

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils


class Migration(migrations.Migration):

    dependencies = [
        ('c_sadicarnot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentabanco',
            options={'managed': True, 'verbose_name_plural': 'Cuentas bancarias'},
        ),
        migrations.AlterField(
            model_name='asiento',
            name='a_favor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sadi_auxiliar_proveedor_id', to='main.Proveedore'),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='condomino',
            field=models.ForeignKey(default=67, on_delete=django.db.models.deletion.PROTECT, related_name='sadi_auxiliar_condomino_id', to='c_sadicarnot.Condomino'),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='tipo_movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sadi_auxiliar_tipo_movimiento_id', to='main.TipoMovimiento'),
        ),
        migrations.AlterField(
            model_name='condomino',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sadi_condomino_condominio_id', to='main.Condominio'),
        ),
        migrations.AlterField(
            model_name='cuentabanco',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sadi_banco_cuenta', to='main.Banco'),
        ),
        migrations.AlterField(
            model_name='cuentabanco',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sadi_cuenta_condominio', to='main.Condominio'),
        ),
        migrations.AlterField(
            model_name='detallemovimiento',
            name='cuenta_contable',
            field=models.ForeignKey(limit_choices_to=django.db.models.query_utils.Q(('clave_mayor', '41'), ('clave_mayor', '51'), ('num_cuenta', '2318'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='sadi_cta_detalle', to='main.CuentaContable', verbose_name='Cuenta Contable Ingreso/Egreso'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='situacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sadi_recibo_situacion_id', to='main.Situacion'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sadi_recibo_tipodoc_id', to='main.TipoDocumento'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='condomino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sadi_movimiento_condomino_id', to='c_sadicarnot.Condomino'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cuenta_banco',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='sadi_movimiento_cuenta_id', to='c_sadicarnot.CuentaBanco'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sadi_movimiento_documento_id', to='c_sadicarnot.Documento'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo_movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sadi_movimiento_tipo_movimiento_id', to='main.TipoMovimiento'),
        ),
    ]
