# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import main.Repocuotas_pb2 as Repocuotas__pb2


class RepocuotasServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.repocuotas = channel.unary_unary(
        '/danielcruzmx.example.grpc.RepocuotasService/repocuotas',
        request_serializer=Repocuotas__pb2.RepocuotasRequest.SerializeToString,
        response_deserializer=Repocuotas__pb2.RepocuotasResponse.FromString,
        )


class RepocuotasServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def repocuotas(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RepocuotasServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'repocuotas': grpc.unary_unary_rpc_method_handler(
          servicer.repocuotas,
          request_deserializer=Repocuotas__pb2.RepocuotasRequest.FromString,
          response_serializer=Repocuotas__pb2.RepocuotasResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'danielcruzmx.example.grpc.RepocuotasService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
