# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Repocuotas.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Repocuotas.proto',
  package='danielcruzmx.example.grpc',
  syntax='proto3',
  serialized_pb=_b('\n\x10Repocuotas.proto\x12\x19\x64\x61nielcruzmx.example.grpc\"2\n\x11RepocuotasRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07hobbies\x18\x02 \x03(\t\"(\n\x12RepocuotasResponse\x12\x12\n\nrepocuotas\x18\x01 \x01(\t2~\n\x11RepocuotasService\x12i\n\nrepocuotas\x12,.danielcruzmx.example.grpc.RepocuotasRequest\x1a-.danielcruzmx.example.grpc.RepocuotasResponseb\x06proto3')
)




_REPOCUOTASREQUEST = _descriptor.Descriptor(
  name='RepocuotasRequest',
  full_name='danielcruzmx.example.grpc.RepocuotasRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='danielcruzmx.example.grpc.RepocuotasRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hobbies', full_name='danielcruzmx.example.grpc.RepocuotasRequest.hobbies', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=97,
)


_REPOCUOTASRESPONSE = _descriptor.Descriptor(
  name='RepocuotasResponse',
  full_name='danielcruzmx.example.grpc.RepocuotasResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='repocuotas', full_name='danielcruzmx.example.grpc.RepocuotasResponse.repocuotas', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=139,
)

DESCRIPTOR.message_types_by_name['RepocuotasRequest'] = _REPOCUOTASREQUEST
DESCRIPTOR.message_types_by_name['RepocuotasResponse'] = _REPOCUOTASRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RepocuotasRequest = _reflection.GeneratedProtocolMessageType('RepocuotasRequest', (_message.Message,), dict(
  DESCRIPTOR = _REPOCUOTASREQUEST,
  __module__ = 'Repocuotas_pb2'
  # @@protoc_insertion_point(class_scope:danielcruzmx.example.grpc.RepocuotasRequest)
  ))
_sym_db.RegisterMessage(RepocuotasRequest)

RepocuotasResponse = _reflection.GeneratedProtocolMessageType('RepocuotasResponse', (_message.Message,), dict(
  DESCRIPTOR = _REPOCUOTASRESPONSE,
  __module__ = 'Repocuotas_pb2'
  # @@protoc_insertion_point(class_scope:danielcruzmx.example.grpc.RepocuotasResponse)
  ))
_sym_db.RegisterMessage(RepocuotasResponse)



_REPOCUOTASSERVICE = _descriptor.ServiceDescriptor(
  name='RepocuotasService',
  full_name='danielcruzmx.example.grpc.RepocuotasService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=141,
  serialized_end=267,
  methods=[
  _descriptor.MethodDescriptor(
    name='repocuotas',
    full_name='danielcruzmx.example.grpc.RepocuotasService.repocuotas',
    index=0,
    containing_service=None,
    input_type=_REPOCUOTASREQUEST,
    output_type=_REPOCUOTASRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REPOCUOTASSERVICE)

DESCRIPTOR.services_by_name['RepocuotasService'] = _REPOCUOTASSERVICE

# @@protoc_insertion_point(module_scope)
