# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-24 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cuota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'menu',
            },
        ),
        migrations.AlterField(
            model_name='cuota',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
