# Generated by Django 2.0 on 2018-08-29 19:33

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180824_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentacontable',
            options={'managed': True, 'ordering': ['num_cuenta'], 'verbose_name_plural': 'Cuentas contables'},
        ),
        migrations.AlterModelOptions(
            name='situacion',
            options={'managed': True, 'verbose_name_plural': 'Tipo situacion pago'},
        ),
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'managed': True, 'verbose_name_plural': 'Tipo documento'},
        ),
        migrations.AlterModelOptions(
            name='tipomovimiento',
            options={'managed': True, 'verbose_name_plural': 'Tipo movimiento'},
        ),
        migrations.AlterField(
            model_name='cuota',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Condominio'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='cuenta_contable',
            field=models.ForeignKey(limit_choices_to=django.db.models.query_utils.Q(clave_mayor='23'), on_delete=django.db.models.deletion.PROTECT, to='main.CuentaContable'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='tipo_movimiento',
            field=models.ForeignKey(default=27, limit_choices_to=django.db.models.query_utils.Q(id='27'), on_delete=django.db.models.deletion.PROTECT, to='main.TipoMovimiento'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Condominio'),
        ),
    ]
